version: '2'
services:
    jhipsterangular-app:
        image: jhipsterangular
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterangular-mysql:3306/jhipsterangular?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterangular-mysql:
        extends:
            file: mysql.yml
            service: jhipsterangular-mysql
